export const  CONSTANTS={
    ADD_CLIENT_REQUESTED: 'ADD_CLIENT_REQUESTED',
    ADD_CLIENTS_PROCESSING: 'ADD_CLIENTS_PROCESSING',
    ADD_CLIENTS_SUCCESS: 'ADD_CLIENTS_SUCCESS',
    ADD_CLIENTS_FAILED: 'ADD_CLIENTS_FAILED',
    CLIENT_LIST_FETCH_REQUESTED: 'CLIENT_LIST_FETCH_REQUESTED',
    CLIENT_LIST_FETCH_PROCESSING: 'CLIENT_LIST_FETCH_PROCESSING',
    CLIENT_LIST_FETCH_SUCCESS: 'CLIENT_LIST_FETCH_SUCCESS',
    CLIENT_LIST_FETCH_FAILED: 'CLIENT_LIST_FETCH_FAILED',

}