
export const CONSTANTS = {
    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    LOGIN_PROCESSING: 'LOGIN_PROCESSING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
}