
export const CONSTANTS = {
    LOGIN_REQUESTED: 'LOGIN_REQUESTED',
    LOGIN_PROCESSING: 'LOGIN_PROCESSING',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    SIGNUP_REQUESTED: 'SIGNUP_REQUESTED',
    SIGNUP_PROCESSING: 'SIGNUP_PROCESSING',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILED: 'SIGNUP_FAILED',
    PROFILE_REQUESTED: 'PROFILE_REQUESTED',
    PROFILE_PROCESSING: 'PROFILE_PROCESSING',
    PROFILE_SUCCESS: 'PROFILE_SUCCESS',
    PROFILE_FAILED: 'PROFILE_FAILED',
}